from . import curso
from . import aula
from . import horario
from . import materia
from . import profesor
from . import inscripcion
from . import pago_mensualidad
from . import examen
from . import nota_alumno
from . import boletin_alumno
from . import reporte
from . import comunicado
from . import asistencia
from . import padre
from . import tarea
from . import envio_tarea
from . import usuario
from . import notificacion
from . import token
from . import estudiante  
from . import comunicado_tracking